In [3]:
import numpy as np

In [4]:
l1 =[1,2,3,4] #list
l1                          

[1, 2, 3, 4]

In [5]:
l1=np.array(l1)
l1

array([1, 2, 3, 4])

In [42]:
l1[2]

3

In [6]:
matrix = [[1,2,3],[4,5,6]]
matrix

[[1, 2, 3], [4, 5, 6]]

In [7]:
matrix= np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
array1 = np.zeros(10) #to create an array with default value 0.
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
array2 = np.ones(10) #to create an array with default value 1.
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
array3 = np.ones((10,10))
array3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.random.random()

0.4506105175644066

In [21]:
random1 = np.random.rand(5) # create array with random number between 0 and 1.
random1

array([0.56901269, 0.91949614, 0.87735761, 0.51566547, 0.96131728])

In [24]:
np.random.randint(4,40)

19

In [23]:
random2= np.random.randint(4,40,10) # create array with random integer numbers in a range.
random2

array([37, 13, 19, 36,  6, 39, 38,  8, 33, 14])

In [10]:
arr1 = np.arange(0,10) # create array in a particular range.
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2 = np.arange(10,1) #can not create a reverse array directly.
print(arr2)

[]


In [13]:
arr3 = np.arange(0,10,2) #create array by skipping individual elements in a range.
arr3

array([0, 2, 4, 6, 8])

In [16]:
equal = np.linspace(0,10,9) #crate an array with equally spaced numbers in a range.
equal

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [19]:
equal2 = np.linspace(0,10,11)
equal2 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
imatrix = np.eye(3) #create an identity matrix.
imatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
random2.reshape(2,5)

array([[37, 13, 19, 36,  6],
       [39, 38,  8, 33, 14]])

In [35]:
random2.reshape(5,2)

array([[37, 13],
       [19, 36],
       [ 6, 39],
       [38,  8],
       [33, 14]])

In [36]:
random2.min()

6

In [37]:
random2.max()

39

In [38]:
random2.argmin() # index of the min element of array.

4

In [39]:
random2.argmax() # index of the max element of array.

5

In [43]:
l = list(random2) # numpy array to list.
l

[37, 13, 19, 36, 6, 39, 38, 8, 33, 14]

In [44]:
random2.shape # gives the shape of the array.

(10,)

In [45]:
matrix.shape #gives the shape of the array.

(2, 3)

In [46]:
random2.dtype

dtype('int32')